# Generated by Django 4.2.1 on 2023-06-05 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_Cache',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='Номер запроса к API')),
                ('address', models.CharField(db_index=True, max_length=200, verbose_name='Адрес')),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90, 'Широта должна быть в диапазоне от -90 до 90'), django.core.validators.MaxValueValidator(90, 'Широта должна быть в диапазоне от -90 до 90')], verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180, 'Долгота должна быть в диапазоне от -180 до 180'), django.core.validators.MaxValueValidator(180, 'Долгота должна быть в диапазоне от -180 до 180')], verbose_name='Долгота')),
                ('requested_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Кэшированный адрес',
                'verbose_name_plural': 'Кэшированные адреса',
            },
        ),
    ]
