# Generated by Django 4.2.1 on 2023-06-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_order_payment_method_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(choices=[('unprocessed', 'Не обработан'), ('en-route', 'В доставке'), ('completed', 'Выполнен')], db_index=True, default=False, verbose_name='Статус заказа'),
        ),
    ]
