# Generated by Django 4.2.1 on 2023-06-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(choices=[('unprocessed', 'Не обработан'), ('en-route', 'В доставке'), ('completed', 'Выполнен')], db_index=True, default='unprocessed', verbose_name='Статус заказа'),
        ),
    ]
