# Generated by Django 4.2.1 on 2023-06-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('non_cash', 'Электронно')], db_index=True, default='cash', max_length=100, verbose_name='Cпособ оплаты'),
        ),
    ]
