# Generated by Django 4.2.1 on 2023-06-02 14:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_called_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90, 'Широта должна быть в диапазоне от -90 до 90'), django.core.validators.MaxValueValidator(90, 'Широта должна быть в диапазоне от -90 до 90')], verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180, 'Долгота должна быть в диапазоне от -180 до 180'), django.core.validators.MaxValueValidator(180, 'Долгота должна быть в диапазоне от -180 до 180')], verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Выберите ресторан для исполнения заказа', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90, 'Широта должна быть в диапазоне от -90 до 90'), django.core.validators.MaxValueValidator(90, 'Широта должна быть в диапазоне от -90 до 90')], verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180, 'Долгота должна быть в диапазоне от -180 до 180'), django.core.validators.MaxValueValidator(180, 'Долгота должна быть в диапазоне от -180 до 180')], verbose_name='Долгота'),
        ),
    ]
